apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.projectName }}-secrets
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  jwt-key: {{ .Values.secrets.jwtKey | quote }}
