apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: supply-chain-security-environments
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  generators:
    - list:
        elements:
          - env: prod
            namespace: hardened-zone
            vFile: values.yaml
  template:
    metadata:
      name: supply-chain-security-{{env}}
    spec:
      project: supply-chain-security
      ignoreDifferences:
        - group: kyverno.io
          kind: ClusterPolicy
          jsonPointers:
            - '.spec.rules[]? | .skipBackgroundRequests?'
            - '.spec.rules[]? | .validate? | .allowExistingViolations?'
            - '.spec.rules[]? | .verifyImages[]? | .useCache?'
            - '.spec.rules[]? | .verifyImages[]? | .signatureAlgorithm?'
            - '.spec.rules[]? | .verifyImages[]? | .attestations[]? | .attestors[]? | .entries[]? | .signatureAlgorithm?'
      source:
        repoURL: https://github.com/davidlihor/k8s-supply-chain-security.git
        targetRevision: HEAD
        path: helm
        helm:
          valueFiles:
            - values.yaml
            - "{{vFile}}"
          parameters:
            - name: "global.namespace"
              value: "{{namespace}}"
            - name: "global.environment"
              value: "{{env}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      syncPolicy:
        managedNamespaceMetadata:
          labels:
            istio-injection: enabled
            environment: "{{env}}"
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
