apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactivities-sql
  namespace: reactivities
  labels:
    app: sql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql
  template:
    metadata:
      labels:
        app: sql
    spec:
      containers:
        - name: sql
          image: mcr.microsoft.com/azure-sql-edge:latest
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "1"
            - name: MSSQL_SA_PASSWORD
              value: "Password@123"
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: false
            readOnlyRootFilesystem: false
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: "0.5"
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: sql
  namespace: reactivities
spec:
  ports:
    - port: 1433
      targetPort: 1433
  selector:
    app: sql
