server {
    listen 8080;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    location /healthz {
        default_type application/json;
        alias /usr/share/nginx/html/healthz.json;
    }

    location /metadata {
        default_type application/json;
        alias /usr/share/nginx/html/metadata.json;
    }

    location /nginx_status {
        stub_status;
        allow 127.0.0.1;
        allow 10.0.0.0/8;
        deny all;
    }
}
